name: 'Mend Slack Notifier'

on:
  discussion:
    types: [labeled]

permissions:
  discussions: read

jobs:
  slack:
    if: contains(github.event.label.name, 'mend-app')
    runs-on: ubuntu-latest
    steps:
      - name: Harden Runner
        uses: step-security/harden-runner@8ca2b8b2ece13480cda6dacd3511b49857a23c09 # v2.5.1
        with:
          egress-policy: audit

      - name: Post to Slack
        id: slack
        uses: slackapi/slack-github-action@e28cf165c92ffef168d23c5c9000cffc8a25e117 # v1.24.0
        with:
          channel-id: 'C05NLTMGCJC'
          # For posting a simple plain text message
          slack-message: '<${{ github.event.discussion.html_url }}|${{ github.event.discussion.title }}>'
        env:
          SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}
